#!/bin/bash
# Automated Stress Testing Script
# Compares your solution (solution.cpp) against a brute-force (brute.cpp)
# using random inputs generated by (gen.cpp).

set -e

echo "Compiling solution, brute-force, and generator..."
g++ -std=c++20 -O2 solution.cpp -o solution
g++ -std=c++20 -O2 brute.cpp -o brute
g++ -std=c++20 -O2 gen.cpp -o gen

echo "Starting stress testing..."
for ((i=1; ; ++i)); do
    ./gen $i > input.txt
    ./solution < input.txt > my_out.txt
    ./brute < input.txt > correct_out.txt

    if diff -u my_out.txt correct_out.txt > /dev/null; then
        echo -ne "Passed Test #$i\r"
    else
        echo ""
        echo "💥 COUNTEREXAMPLE FOUND on Test #$i!"
        echo "=== INPUT ==="
        cat input.txt
        echo "=== YOUR OUTPUT ==="
        cat my_out.txt
        echo "=== EXPECTED OUTPUT ==="
        cat correct_out.txt
        break
    fi
done
